package comart.rudbman.bridge;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import comart.rudbman.bridge.support.H2;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * {@code DESCRIBE kind: "ddl"} over a table carrying every feature the reverse
 * generator has to reproduce.
 *
 * <p>The one test that actually pins the quality of the reconstruction is
 * {@link #reverseGeneratedDdlReplays}: string assertions only prove that the
 * expected words appear somewhere, while replaying the statement into a second
 * schema and comparing the metadata proves that what came out is the table that
 * went in. Everything else here is a readability check on top of that.
 */
class DdlTest {

    private long session;

    @BeforeEach
    void setUp() {
        session = H2.open(H2.freshUrl());
        H2.exec(session, "create schema ddlsrc");
        H2.exec(session, "create table ddlsrc.parent ("
                + "id int not null, code varchar(20) not null, "
                + "constraint pk_parent primary key (id, code))");
        H2.exec(session, "create table ddlsrc.child ("
                + "id bigint generated by default as identity primary key, "
                + "parent_id int not null, "
                + "parent_code varchar(20) not null, "
                // A reserved word, upper case: only the keyword forces quoting.
                + "\"ORDER\" int default 0 not null, "
                // Mixed case on a server that folds to upper: only the case does.
                + "\"mixedCase\" varchar(10), "
                + "amount decimal(20,8), "
                + "note varchar(100) default 'x', "
                + "constraint fk_child_parent foreign key (parent_id, parent_code) "
                + "references ddlsrc.parent(id, code) on delete cascade)");
        H2.exec(session, "comment on table ddlsrc.child is 'child rows'");
        H2.exec(session, "comment on column ddlsrc.child.note is 'a note'");
        H2.exec(session, "create index idx_child_note on ddlsrc.child(note)");
    }

    @AfterEach
    void tearDown() {
        H2.close(session);
    }

    private JsonObject ddl(String schema, String table, String source) {
        JsonObject req = new JsonObject();
        req.addProperty("kind", "ddl");
        req.addProperty("schema", schema);
        req.addProperty("table", table);
        if (source != null) {
            req.addProperty("source", source);
        }
        JsonObject resp = H2.call(Ops.DESCRIBE, session, 0, req).json();
        assertEquals("ddl", resp.get("kind").getAsString());
        return resp;
    }

    private String text(String schema, String table, String source) {
        return ddl(schema, table, source).get("ddl").getAsString();
    }

    @Test
    void reverseGeneratedDdlCarriesEveryFeature() {
        String sql = text("DDLSRC", "CHILD", "metadata");

        assertContains(sql, "CREATE TABLE DDLSRC.CHILD (");
        // Plain upper-case names stay bare; quoting all of them would make the
        // statement unreadable.
        assertContains(sql, "PARENT_ID INTEGER NOT NULL");
        // A reserved word has to be quoted even though its case is fine.
        assertContains(sql, "\"ORDER\" INTEGER DEFAULT 0 NOT NULL");
        // Mixed case has to be quoted even though it is not a keyword.
        assertContains(sql, "\"mixedCase\" CHARACTER VARYING(10)");
        assertContains(sql, "AMOUNT DECIMAL(20, 8)");
        assertContains(sql, "NOTE CHARACTER VARYING(100) DEFAULT 'x'");
        assertContains(sql, "GENERATED BY DEFAULT AS IDENTITY");
        assertContains(sql, "PRIMARY KEY (ID)");
        assertContains(sql, "CONSTRAINT FK_CHILD_PARENT FOREIGN KEY (PARENT_ID, PARENT_CODE)");
        assertContains(sql, "REFERENCES DDLSRC.PARENT (ID, CODE)");
        assertContains(sql, "ON DELETE CASCADE");
        assertContains(sql, "CREATE INDEX IDX_CHILD_NOTE ON DDLSRC.CHILD (NOTE)");
        assertContains(sql, "COMMENT ON TABLE DDLSRC.CHILD IS 'child rows'");
        assertContains(sql, "COMMENT ON COLUMN DDLSRC.CHILD.NOTE IS 'a note'");

        // The identity column's size is bits, not a length.
        assertFalse(sql.contains("BIGINT("), sql);
        assertFalse(sql.contains("INTEGER("), sql);
        // H2 creates an index behind every foreign key. Emitting it would make
        // the statement fail to replay, because adding the key creates it again.
        assertFalse(sql.contains("FK_CHILD_PARENT_INDEX"), sql);
        // Nor is the primary key's own index a separate statement.
        assertFalse(sql.contains("CREATE UNIQUE INDEX"), sql);
    }

    @Test
    void compositePrimaryKeyKeepsItsColumnOrder() {
        String sql = text("DDLSRC", "PARENT", "metadata");
        assertContains(sql, "CONSTRAINT PK_PARENT PRIMARY KEY (ID, CODE)");
    }

    @Test
    void h2AnswersFromItsOwnScript() {
        JsonObject resp = ddl("DDLSRC", "CHILD", null);
        assertEquals("native", resp.get("source").getAsString(), resp.toString());
        String sql = resp.get("ddl").getAsString();
        assertContains(sql, "\"DDLSRC\".\"CHILD\"");
        assertContains(sql, "IDX_CHILD_NOTE");
        // SCRIPT prefixes the whole database; only this table's statements
        // survive the filter.
        assertFalse(sql.contains("CREATE USER"), sql);
        assertFalse(sql.contains("CREATE SCHEMA"), sql);
        assertFalse(sql.contains("SELECT COUNT(*)"), sql);
    }

    @Test
    void metadataSourceIsSelectable() {
        assertEquals("metadata", ddl("DDLSRC", "CHILD", "metadata").get("source").getAsString());
    }

    /**
     * Replays the reconstruction into a second schema and compares the two
     * tables through the metadata the reconstruction was built from.
     */
    @Test
    void reverseGeneratedDdlReplays() {
        H2.exec(session, "create schema ddldst");
        for (String table : new String[]{"PARENT", "CHILD"}) {
            // The statement names its own schema; retargeting it is a rename,
            // and no literal in this fixture contains the schema name.
            String sql = text("DDLSRC", table, "metadata").replace("DDLSRC", "DDLDST");
            for (String stmt : sql.split(";")) {
                if (!stmt.isBlank()) {
                    H2.exec(session, stmt.trim());
                }
            }
        }

        assertEquals(structure("DDLSRC", "CHILD"), structure("DDLDST", "CHILD"));
        assertEquals(structure("DDLSRC", "PARENT"), structure("DDLDST", "PARENT"));

        // And the comments survived, which the structure signature deliberately
        // leaves out so that a comment change cannot masquerade as a shape change.
        JsonArray copied = describe("tables", "schema", "DDLDST", "table", "CHILD");
        assertEquals("child rows", copied.get(0).getAsJsonObject().get("remarks").getAsString());
        JsonArray cols = describe("columns", "schema", "DDLDST", "table", "CHILD");
        assertEquals("a note", pick(cols, "NOTE").get("remarks").getAsString());
    }

    @Test
    void unknownTableIsReportedAsSuch() {
        JsonObject req = new JsonObject();
        req.addProperty("kind", "ddl");
        req.addProperty("schema", "DDLSRC");
        req.addProperty("table", "NO_SUCH_TABLE");
        req.addProperty("source", "metadata");
        JsonObject err = H2.call(Ops.DESCRIBE, session, 0, req).error();
        assertEquals("sql", err.get("kind").getAsString());
    }

    @Test
    void ddlRequiresATable() {
        JsonObject req = new JsonObject();
        req.addProperty("kind", "ddl");
        req.addProperty("schema", "DDLSRC");
        assertEquals("protocol",
                H2.call(Ops.DESCRIBE, session, 0, req).error().get("kind").getAsString());
    }

    @Test
    void anUnknownSourceIsAProtocolError() {
        JsonObject req = new JsonObject();
        req.addProperty("kind", "ddl");
        req.addProperty("schema", "DDLSRC");
        req.addProperty("table", "CHILD");
        req.addProperty("source", "guess");
        assertEquals("protocol",
                H2.call(Ops.DESCRIBE, session, 0, req).error().get("kind").getAsString());
    }

    // --------------------------------------------------------------- helpers

    /**
     * A schema-independent signature of a table: the columns with their types
     * and nullability, the primary key, the foreign keys with their rules and
     * the indexes. Object names of the referenced schema are normalised away so
     * that the same table in two schemas compares equal.
     */
    private String structure(String schema, String table) {
        List<String> parts = new ArrayList<>();
        for (JsonElement e : describe("columns", "schema", schema, "table", table)) {
            JsonObject c = e.getAsJsonObject();
            parts.add("col " + s(c, "name") + " " + s(c, "type_name") + " size=" + s(c, "size")
                    + " digits=" + s(c, "digits") + " nullable=" + s(c, "is_nullable")
                    + " default=" + s(c, "default") + " auto=" + s(c, "auto_increment"));
        }
        for (JsonElement e : describe("primary_keys", "schema", schema, "table", table)) {
            JsonObject k = e.getAsJsonObject();
            parts.add("pk " + s(k, "seq") + " " + s(k, "column"));
        }
        for (JsonElement e : describe("imported_keys", "schema", schema, "table", table)) {
            JsonObject k = e.getAsJsonObject();
            parts.add("fk " + s(k, "seq") + " " + s(k, "fk_column") + " -> "
                    + s(k, "pk_table") + "." + s(k, "pk_column")
                    + " del=" + s(k, "delete_rule") + " upd=" + s(k, "update_rule"));
        }
        for (JsonElement e : describe("indexes", "schema", schema, "table", table)) {
            JsonObject i = e.getAsJsonObject();
            parts.add("ix " + s(i, "non_unique") + " " + s(i, "ordinal") + " " + s(i, "column"));
        }
        return String.join("\n", parts);
    }

    private static String s(JsonObject o, String key) {
        JsonElement e = o.get(key);
        return e == null || e.isJsonNull() ? "-" : e.getAsString();
    }

    private static JsonObject pick(JsonArray arr, String name) {
        for (JsonElement e : arr) {
            if (name.equals(e.getAsJsonObject().get("name").getAsString())) {
                return e.getAsJsonObject();
            }
        }
        throw new AssertionError("no such column: " + name + " in " + arr);
    }

    private JsonArray describe(String kind, String... kv) {
        JsonObject req = new JsonObject();
        req.addProperty("kind", kind);
        for (int i = 0; i < kv.length; i += 2) {
            req.addProperty(kv[i], kv[i + 1]);
        }
        return H2.call(Ops.DESCRIBE, session, 0, req).json().get("items").getAsJsonArray();
    }

    private static void assertContains(String haystack, String needle) {
        assertTrue(haystack.contains(needle), "expected to find\n  " + needle + "\nin\n" + haystack);
    }
}
